CREATE TABLE jeoGames (
  id INTEGER PRIMARY KEY,
  userId TEXT,
  public INTEGER,
  gameTitle TEXT,
  basePoints INTEGER,
  topicLabel1 TEXT,
  topic1Question1 TEXT,
  topic1Question2 TEXT,
  topic1Question3 TEXT,
  topic1Question4 TEXT,
  topic1Question5 TEXT,
  topic1Answer1 TEXT,
  topic1Answer2 TEXT,
  topic1Answer3 TEXT,
  topic1Answer4 TEXT,
  topic1Answer5 TEXT,
  topicLabel2 TEXT,
  topic2Question1 TEXT,
  topic2Question2 TEXT,
  topic2Question3 TEXT,
  topic2Question4 TEXT,
  topic2Question5 TEXT,
  topic2Answer1 TEXT,
  topic2Answer2 TEXT,
  topic2Answer3 TEXT,
  topic2Answer4 TEXT,
  topic2Answer5 TEXT,
  topicLabel3 TEXT,
  topic3Question1 TEXT,
  topic3Question2 TEXT,
  topic3Question3 TEXT,
  topic3Question4 TEXT,
  topic3Question5 TEXT,
  topic3Answer1 TEXT,
  topic3Answer2 TEXT,
  topic3Answer3 TEXT,
  topic3Answer4 TEXT,
  topic3Answer5 TEXT,
  topicLabel4 TEXT,
  topic4Question1 TEXT,
  topic4Question2 TEXT,
  topic4Question3 TEXT,
  topic4Question4 TEXT,
  topic4Question5 TEXT
);

CREATE TABLE validated (
  userId TEXT PRIMARY KEY,
  name TEXT,
  valid INTEGER NOT NULL DEFAULT 0,
  special INTEGER NOT NULL DEFAULT 0
);